### ISSUE TITLE
Library doesn't work with Home Hub 3000

### ISSUE THREAD

**Issue by superlowburn** [iMicknl/python-sagemcom-api#2] opened 2020-11-03 00:19 UTC
I have
![Screen Shot 2020-11-02 at 8 07 49 PM](https://user-images.githubusercontent.com/24779772/97932744-2aa0d900-1d47-11eb-9540-06790b23ad73.png)

<pre>
cat runit.py && python3 runit.py

(venv) smallett@steves-MacBook-Air python-sagemcom-api-master % python3 runit.py 
Traceback (most recent call last):
  File "/Users/smallett/Projects/python-sagemcom-api-master/runit.py", line 11, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/smallett/Projects/python-sagemcom-api-master/runit.py", line 8, in main
    device_info = await sagemcom.get_device_info()
  File "/Users/smallett/Projects/python-sagemcom-api-master/sagemcom_api/client.py", line 222, in get_device_info
    bootloader_version=info["BootloaderVersion"]
KeyError: 'BootloaderVersion'
(venv) smallett@steves-MacBook-Air python-sagemcom-api-master % cat runit.py && python3 runit.py 
import asyncio
from sagemcom_api import SagemcomClient, EncryptionMethod

async def main():
    # Choose EncryptionMethod.MD5, EncryptionMethod.SHA512 or EncryptionMethod.Unknown
    sagemcom = SagemcomClient('192.168.2.1', 'admin', '<My Password>!', EncryptionMethod.MD5)

    device_info = await sagemcom.get_device_info()
    print(device_info)

asyncio.run(main())
Traceback (most recent call last):
  File "/Users/smallett/Projects/python-sagemcom-api-master/runit.py", line 11, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/smallett/Projects/python-sagemcom-api-master/runit.py", line 8, in main
    device_info = await sagemcom.get_device_info()
  File "/Users/smallett/Projects/python-sagemcom-api-master/sagemcom_api/client.py", line 222, in get_device_info
    bootloader_version=info["BootloaderVersion"]
KeyError: 'BootloaderVersion'
</pre>

And logged into the admin I DO have xhf files, but cannot run $.xmo.getValuesTree("Device/DeviceInfo")

![Screen Shot 2020-11-02 at 8 16 31 PM](https://user-images.githubusercontent.com/24779772/97933151-4fe21700-1d48-11eb-8c0b-385c7c9756d2.png)

![Screen Shot 2020-11-02 at 8 17 14 PM](https://user-images.githubusercontent.com/24779772/97933184-68523180-1d48-11eb-8bc9-f153ad17917a.png)

Any help would be greatly appreciated!

**Comment by iMicknl** [comment] 2020-11-03 19:38
It looks like your model is using a different firmware... Are the XHR reponses in the networking tab only HTML pages or are there also JSON responses?

**Comment by superlowburn** [comment] 2020-11-03 20:56
Thanks for replying. 

`{"reply":{"uid":0,"id":33,"error":{"code":16777216,"description":"XMO_REQUEST_NO_ERR"},"actions":[{"uid":1,"id":0,"error":{"code":16777238,"description":"XMO_NO_ERR"},"callbacks":[{"uid":1,"result":{"code":16777238,"description":"XMO_NO_ERR"},"xpath":"Device","parameters":{}}]}],"events":[{"uid":1,"id":20,"type":"VALUE_CHANGE","xpath":"Device\/IP\/Interfaces\/Interface[@uid='4']\/Status","parameters":{"value":"LOWERLAYERDOWN","capability":{"name":"Status","type":"interface:Interface:Status xmo:int32 xmo:number xmo:value","flags":{"value":true,"status":true,"xml-child":true},"default-value":"DOWN","restrictions":{"enum-values":[{"name":"UP","value":"0"},{"name":"DOWN","value":"1"},{"name":"UNKNOWN","value":"2"},{"name":"DORMANT","value":"3"},{"name":"NOTPRESENT","value":"4"},{"name":"LOWERLAYERDOWN","value":"5"},{"name":"ERROR","value":"6"}]}}}},{"uid":2,"id":20,"type":"VALUE_CHANGE","xpath":"Device\/IP\/Interfaces\/Interface[@uid='4']\/Status","parameters":{"value":"DORMANT","capability":{"name":"Status","type":"interface:Interface:Status xmo:int32 xmo:number xmo:value","flags":{"value":true,"status":true,"xml-child":true},"default-value":"DOWN","restrictions":{"enum-values":[{"name":"UP","value":"0"},{"name":"DOWN","value":"1"},{"name":"UNKNOWN","value":"2"},{"name":"DORMANT","value":"3"},{"name":"NOTPRESENT","value":"4"},{"name":"LOWERLAYERDOWN","value":"5"},{"name":"ERROR","value":"6"}]}}}}]}}`

![Screen Shot 2020-11-03 at 4 54 08 PM](https://user-images.githubusercontent.com/24779772/98039664-6db98580-1df5-11eb-885f-9f8a0bd80277.png)

**Comment by iMicknl** [comment] 2020-11-03 21:03
Could you try `$.xmo.getValuesTree("*")` in your console? And `$.xmo.getValuesTree("*/*")` and `$.xmo.getValuesTree("*/*/*")`? 

It looks like the json-req API is present in your router. We will need to have a look what is different in the responses, so we can modify the API.

**Comment by superlowburn** [comment] 2020-11-03 21:05
Just found this too: 
![Screen Shot 2020-11-03 at 5 03 45 PM](https://user-images.githubusercontent.com/24779772/98040484-ba519080-1df6-11eb-975c-77e6793b722b.png)

**Comment by superlowburn** [comment] 2020-11-03 21:07
Console: 
![Screen Shot 2020-11-03 at 5 06 16 PM](https://user-images.githubusercontent.com/24779772/98040602-e9680200-1df6-11eb-9f76-383d41904ad7.png)

**Comment by iMicknl** [comment] 2020-11-03 21:40
Could you open the `json-req` responses and put them here? (Please remove personal information, or send them to the email in my GitHub). It would be good to see some of the examples, especially the request when you are on the device overview page.

**Comment by superlowburn** [comment] 2020-11-04 00:06
Sent. Tnx

**Comment by superlowburn** [comment] 2020-11-04 03:35
This isn't my usual forte, but I was able to use the UI with postman capturing responses to do a successful reboot API call... after a lot of head banging.  8^)

**Comment by iMicknl** [comment] 2021-01-18 16:46
@superlowburn sorry for the late response. Are you still planning on using this library? I will take some time the coming weeks to rewrite the library.

Could you share those calls / JSON with me via email? (see profile)

**Comment by simlaf** [comment] 2021-03-12 18:45
Just wanted to mention that I have the same model and it's working fine for me.

**Comment by iMicknl** [comment] 2021-04-09 10:09
I will close this for now, since @simlaf confirmed that it should be working.

Feel free to reopen if this issue is still present.

**Closed by iMicknl** 2021-04-09 10:09 UTC
Labels: new-device
